### ISSUE TITLE
patrec_gpu_machines.txt  cannot be found

### ISSUE THREAD

**Issue by ZiyangLiu** [ssudholt/phocnet#4]
Hello, 
I try to install phocnet on AWS. It reports the error: 

CMake Error at cmake/Cuda.cmake:77 (file):
  file STRINGS file "/home/ubuntu/src/phocnet/caffe/patrec_gpu_machines.txt"
  cannot be read.
Call Stack (most recent call first):
  cmake/Cuda.cmake:153 (caffe_detect_patrec_gpus)
  cmake/Cuda.cmake:314 (caffe_select_nvcc_arch_flags)
  cmake/Dependencies.cmake:77 (include)
  CMakeLists.txt:46 (include)

There is no patrec_gpu_machines.txt in that directory. 
Do you know why this happen? 
Thank you very much.

**Comment by ssudholt** [comment]
You should run cmake with
`cmake -DCUDA_ARCH_NAME=Auto`
